### ISSUE TITLE
joesandbox_crits proxy issues...

### ISSUE THREAD

**Issue by ericwentz** [joesecurity/joesandbox_crits#1]
We're trying to run this service behind a proxy server.  The service does not appear to honor the proxy which is defined in the CRITs Control Panel.  has anybody else had any success in getting this service to work behind a proxy?

Thanks
Eric Wentz
Eaton Corp
(440)523-2220

**Comment by joesecurity** [comment]
I've added a setting for using the CRITs proxy. Let me know if it works. You'll find the code in the `proxy` branch.

https://github.com/joesecurity/joesandbox_crits/tree/proxy

**Comment by joesecurity** [comment]
Committed to the master branch.
